#ifndef MAIN_CONSTANTS_H
#define MAIN_CONSTANTS_H

enum GameMode {
    GAME_MODE_KONAMI_LOGO,
    GAME_MODE_TITLE_SCREEN,
    GAME_MODE_MAIN_MENU,
    GAME_MODE_UNK_3,
    GAME_MODE_IN_GAME,
    GAME_MODE_GAME_OVER,
    GAME_MODE_CREDITS,
    GAME_MODE_INTRO_CUTSCENE,
    GAME_MODE_BOSS_RUSH_MENU,
    GAME_MODE_UNK_9,
    GAME_MODE_SOUL_TRADE_MENU,
    GAME_MODE_SOUND_TEST_MENU,
    GAME_MODE_LICENSED_BY_NINTENDO,
    GAME_MODE_RESET,
    GAME_MODE_DEBUG,
    GAME_MODE_UNK_F,
    GAME_MODE_DEBUG_EXIT,
    GAME_MODE_DEBUG_1967,
    GAME_MODE_DEBUG_2229,
    GAME_MODE_DEBUG_2739,
    GAME_MODE_DEBUG_4531,

    GAME_MODE_COUNT
};

#endif /* MAIN_CONSTANTS_H */
